# Generated by Django 3.2.8 on 2021-11-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(choices=[('N', 'Not started'), ('P', 'In progress'), ('D', 'Done')], max_length=1),
        ),
    ]
